/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.vsn.view;

import br.com.vsn.controller.ContaController;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;

/**
 *
 * @author vitor
 */
public class PagamentoContasPagarView extends javax.swing.JInternalFrame {

    private ContaController cc;
    private static int index=0;
    private static double valor;
    private static int id;
    
    public void setIndex(int index){
        this.index = index;
    }
    
    NumberFormat formatter = new DecimalFormat("#0.00");
    
        DateFormat df = new SimpleDateFormat("dd/MM/yyyy");
    /**
     * Creates new form CadastroContaView
     */
    public PagamentoContasPagarView() throws Exception {
        
        cc = new ContaController();
        initComponents();
        
        Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
        int lar = (int) d.getWidth();
        int alt = (int) d.getHeight();
        this.setLocation((lar - this.getSize().width) / 2, (alt - this.getSize().height)/6);
        
        comboBoxVezes.setEnabled(false);
        comboBoxVezes.setSelectedIndex(0);
        cc.getConta().setVezes(1);
        
        if(cc.getContas().size()<=0){
            System.out.println("ERRO");
        }else{
            this.exibirDados();
        }
        
    }
    

    public ContaController getCc() {
        return cc;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        inputTitulo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        inputValor = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        comboBoxVezes = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        buttonPagar = new javax.swing.JButton();
        buttonInicioT = new javax.swing.JButton();
        buttonProximo = new javax.swing.JButton();
        buttonFinalT = new javax.swing.JButton();
        buttonAnterior = new javax.swing.JButton();
        inputDataCompra = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        inputValorParcela = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        inputPagamento = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        inputSituacao = new javax.swing.JTextField();
        inputValorRestante = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        comboBoxVezesRestantes = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        inputDataVencimento = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();

        setClosable(true);
        setIconifiable(true);
        setTitle("Recebimento de Titulos");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFocusTraversalPolicyProvider(true);

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("RECEBIMENTO DE TITULOS");

        jLabel2.setText("Título:");

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${cc.conta.titulo}"), inputTitulo, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        inputTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputTituloActionPerformed(evt);
            }
        });

        jLabel3.setText("Valor: ");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${cc.conta.valor}"), inputValor, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jLabel5.setText("Vezes:");

        comboBoxVezes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 vez", "2 vezes", "3 vezes", "4 vezes" }));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${cc.conta.vezes}"), comboBoxVezes, org.jdesktop.beansbinding.BeanProperty.create("selectedItem"));
        bindingGroup.addBinding(binding);

        comboBoxVezes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxVezesActionPerformed(evt);
            }
        });

        jLabel6.setText("Data da Primeira Parcela:");

        buttonPagar.setText("Receber Titulo");
        buttonPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPagarActionPerformed(evt);
            }
        });

        buttonInicioT.setText("|<");
        buttonInicioT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonInicioTActionPerformed(evt);
            }
        });

        buttonProximo.setText(">>");
        buttonProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonProximoActionPerformed(evt);
            }
        });

        buttonFinalT.setText(">|");
        buttonFinalT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFinalTActionPerformed(evt);
            }
        });

        buttonAnterior.setText("<<");
        buttonAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAnteriorActionPerformed(evt);
            }
        });

        inputDataCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputDataCompraActionPerformed(evt);
            }
        });

        jLabel7.setText("Pagamento:");

        jLabel8.setText("Valor Parcela:");

        inputPagamento.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jLabel9.setText("Situação:");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${cc.conta.situacao}"), inputSituacao, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jLabel4.setText("Valor Restante:");

        jLabel10.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Dados de Parcelamento");

        jLabel11.setText("Restantes:");

        comboBoxVezesRestantes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 vez", "2 vezes", "3 vezes", "4 vezes" }));
        comboBoxVezesRestantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxVezesRestantesActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Dados de Pagamento");

        jLabel13.setText("Vencimento Prox. Parcela:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboBoxVezesRestantes, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(inputValorRestante, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(inputTitulo))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel13)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(inputDataVencimento, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel5)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(comboBoxVezes, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(inputValor, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(3, 3, 3)
                                            .addComponent(jLabel6))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addGap(17, 17, 17)
                                            .addComponent(jLabel8)))
                                    .addGap(6, 6, 6)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(inputValorParcela, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                                        .addComponent(inputDataCompra)))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jSeparator2)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonPagar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(buttonInicioT)
                        .addGap(31, 31, 31)
                        .addComponent(buttonAnterior)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                        .addComponent(buttonProximo)
                        .addGap(36, 36, 36)
                        .addComponent(buttonFinalT)
                        .addGap(42, 42, 42))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inputPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(107, 151, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(inputTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputDataCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel3))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(comboBoxVezes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(inputValorParcela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(inputValorRestante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxVezesRestantes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(inputDataVencimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(inputSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonProximo)
                    .addComponent(buttonAnterior)
                    .addComponent(buttonInicioT)
                    .addComponent(buttonFinalT))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonPagar)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleDescription("");

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPagarActionPerformed
        
        DateFormat df = new SimpleDateFormat("dd/MM/yyyy");
        int x =cc.buscaContaVezesP(id);
        Calendar dat = cc.getContas().get(index).getDataVencimento();
        id = cc.getContas().get(index).getId();
        valor = cc.buscaContaValorP(id) - Double.parseDouble(inputPagamento.getText());
        cc.efetuarPagamento(id, valor,dat);
        if(x == 1)
            x=2;
        if(comboBoxVezesRestantes.getSelectedIndex() > 0){
            cc.reduzParcela(x-1, id);
            comboBoxVezesRestantes.setSelectedIndex(cc.buscaContaVezesP(id)-1);
            Calendar c = Calendar.getInstance();
            c.setTime(dat.getTime());
            c.set(Calendar.MONTH,c.get(Calendar.MONTH)+1 );
            cc.updateVencimento(id,c);
            inputDataVencimento.setText(""+df.format(c.getTime()));
        }
            
        inputValorRestante.setText(""+formatter.format(valor).replace(",", "."));
        
        if(Double.parseDouble(inputValorRestante.getText()) <= 0 || Double.parseDouble(inputValorRestante.getText()) < 1){
            buttonPagar.setEnabled(false);
            inputPagamento.setText("0.00");
        }
        
        if(Double.parseDouble(inputValorRestante.getText()) >= 0 && Double.parseDouble(inputValorRestante.getText())< 1){
            id = cc.getContas().get(index).getId();
            cc.alterarSituacao(id,dat);
            inputSituacao.setText(cc.retornaContaSituacao(id));
        }
        if(inputSituacao.getText().equals("FECHADO")){
            inputSituacao.setForeground(Color.red);
        }else{
            inputSituacao.setForeground(Color.green);
        }
        
    }//GEN-LAST:event_buttonPagarActionPerformed

    private void comboBoxVezesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxVezesActionPerformed
        cc.getConta().setVezes(comboBoxVezes.getSelectedIndex()+1);
    }//GEN-LAST:event_comboBoxVezesActionPerformed

    
    
    
    
    private void inputTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputTituloActionPerformed
        
        
        
    }//GEN-LAST:event_inputTituloActionPerformed

    private void inputDataCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputDataCompraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputDataCompraActionPerformed

    private void comboBoxVezesRestantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxVezesRestantesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxVezesRestantesActionPerformed

    private void buttonInicioTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonInicioTActionPerformed
        index = 0;
        exibirDados();
    }//GEN-LAST:event_buttonInicioTActionPerformed

    private void buttonAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAnteriorActionPerformed
        if(index > 0){
            anterior();
        }
        exibirDados();
    }//GEN-LAST:event_buttonAnteriorActionPerformed

    private void buttonFinalTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFinalTActionPerformed
        index = cc.getContas().size()-1;
        exibirDados();
    }//GEN-LAST:event_buttonFinalTActionPerformed

    private void buttonProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonProximoActionPerformed

        if(index < cc.getContas().size()-1){
            posterior();
        }
        exibirDados();
    }//GEN-LAST:event_buttonProximoActionPerformed

    public void limpaCampos(){
        inputTitulo.setText("");
        inputValor.setText("");
        comboBoxVezes.setEnabled(false);
        comboBoxVezes.setSelectedIndex(0);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAnterior;
    private javax.swing.JButton buttonFinalT;
    private javax.swing.JButton buttonInicioT;
    private javax.swing.JButton buttonPagar;
    private javax.swing.JButton buttonProximo;
    public static javax.swing.JComboBox<String> comboBoxVezes;
    public static javax.swing.JComboBox<String> comboBoxVezesRestantes;
    public static javax.swing.JTextField inputDataCompra;
    public static javax.swing.JTextField inputDataVencimento;
    public static javax.swing.JTextField inputPagamento;
    public static javax.swing.JTextField inputSituacao;
    public static javax.swing.JTextField inputTitulo;
    public static javax.swing.JTextField inputValor;
    public static javax.swing.JTextField inputValorParcela;
    public static javax.swing.JTextField inputValorRestante;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

    public int anterior(){
        return --index;
    }
    public int posterior(){
        return ++index;
    }
    
    
    public void exibirDados(){
        cc= new ContaController();
        
        id = cc.getContas().get(index).getId();
        Calendar c = cc.buscaDataVencimento(id);
        double valor = cc.getContas().get(index).getValor();
        int vezes = cc.getContas().get(index).getVezes();
        inputTitulo.setText(cc.getContas().get(index).getTitulo());
        inputDataCompra.setText(""+df.format(cc.getContas().get(index).getDataCompra().getTime()));
        inputDataVencimento.setText(""+df.format(cc.getContas().get(index).getDataVencimento().getTime()));
        inputSituacao.setText(cc.getContas().get(index).getSituacao());
        inputValorRestante.setText(""+formatter.format(cc.getContas().get(index).getValorPagar()).replace(",", "."));
        comboBoxVezesRestantes.setSelectedIndex((cc.getContas().get(index).getVezesPagar()-1));
        this.desabilitarComponentes();
        if(vezes == 1){
            inputPagamento.setText(""+formatter.format(valor).replace(",", "."));
            inputValorParcela.setText(""+formatter.format(valor).replace(",", "."));
        }else{
           inputValorParcela.setText(""+formatter.format(((valor)/vezes)).replace(",", "."));
           inputPagamento.setText(""+formatter.format(((valor)/vezes)).replace(",", "."));
        }
        comboBoxVezes.setSelectedIndex(vezes-1);
        inputValor.setText(""+formatter.format((Double.parseDouble(inputValorParcela.getText())*(comboBoxVezes.getSelectedIndex()+1))).replace(",", "."));
       
        if(Double.parseDouble(inputValorRestante.getText()) <= 0 || Double.parseDouble(inputValorRestante.getText()) < 1){
            buttonPagar.setEnabled(false);
            inputPagamento.setText("0.00");
        }else{
            buttonPagar.setEnabled(true);
        }
        
        if(inputSituacao.getText().equals("FECHADO")){
            inputSituacao.setForeground(Color.red);
        }else{
            inputSituacao.setForeground(Color.green);
        }
    }
    
    public static void desabilitarComponentes(){
        inputTitulo.setEditable(false);
        inputValor.setEditable(false);
        inputDataCompra.setEditable(false);
        inputSituacao.setEditable(false);
        inputValorParcela.setEditable(false);
        inputPagamento.setEditable(false);
        inputValorRestante.setEditable(false);
        comboBoxVezesRestantes.setEnabled(false);
        inputDataVencimento.setEditable(false);
    }
    
}
