
package br.com.vsn.view;

import br.com.vsn.controller.FornecedorController;
import br.com.vsn.model.Fornecedor;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vitor
 */
public class PesquisarFornecedorView extends javax.swing.JInternalFrame {

    private static int id;
    SimpleDateFormat sdf;
    static Fornecedor fornecedor;
    
    public static int getId() {
        return id;
    }

    public static void setId(int id) {
        PesquisarFornecedorView.id = id;
    }
    
    
    /**
     * Creates new form PesquisarView
     */
    public PesquisarFornecedorView() {
        sdf = new SimpleDateFormat("dd/MM/yyyy");
        initComponents();
        
        Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
        double lar =d.getWidth();
        int alt = (int) d.getHeight();
        this.setLocation((int) ((lar - this.getSize().width) / 2), (alt - this.getSize().height)/6);
        initComponents();
        
        try {
            this.preencherTabela();
        } catch (Exception ex) {
            Logger.getLogger(PesquisarFornecedorView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setClosable(true);
        setTitle("Pesquisar Cliente");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Razão Social", "CNPJ", "Telefone", "Situação"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(10);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(200);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(80);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(80);
            jTable1.getColumnModel().getColumn(4).setPreferredWidth(80);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 868, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        if(evt.getClickCount() == 2){
          try {
                this.id = this.valorCollun();
                FornecedorController cc = new FornecedorController();
                fornecedor = cc.pesquisarUnico(id).get(0);
                this.valoresInputFornecedor();
                FornecedorView.ativarInputCadastrar();
                FornecedorView.inputId.setEnabled(true);
                this.dispose();
            } catch (Exception ex) {
                Logger.getLogger(PesquisarFornecedorView.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jTable1MouseClicked



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
    
    public void preencherTabela() throws Exception{
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        FornecedorController cc = new FornecedorController();
        DefaultTableModel modelo = (DefaultTableModel)jTable1.getModel();
        modelo.setNumRows(0);
        for(int i=0; i<cc.getFornecedores().size(); i++){
            modelo.addRow(new Object[]{
             cc.getFornecedores().get(i).getId(),
             cc.getFornecedores().get(i).getRazaoSocial(),
             cc.getFornecedores().get(i).getCnpj(),
             cc.getFornecedores().get(i).getTelefone(),
             cc.getFornecedores().get(i).getSituacao()
             });
        }
        
    }
    
    public int valorCollun(){
        int row = jTable1.getSelectedRow();
        Object value = null;
        String converteValueString = "";
         if (row > -1) { //então tem ítem selecionado
             value = jTable1.getValueAt(row, 0);
         }
         converteValueString = ""+value;
         id = Integer.parseInt(converteValueString);
         return id;
   }
    
    public void valoresInputFornecedor(){
        FornecedorView.inputId.setText(""+fornecedor.getId());
        FornecedorView.inputRazaoSocial.setText(""+fornecedor.getRazaoSocial());
        FornecedorView.inputNomeFantasia.setText(""+fornecedor.getNomeFantasia());
        FornecedorView.comboIcms.setSelectedItem((String) fornecedor.getContribuinteIcms());
        FornecedorView.inputCnpj.setText(""+fornecedor.getCnpj());
        FornecedorView.inputInscricaoEstadual.setText(""+fornecedor.getInscricaoEstadual());
        FornecedorView.inputLongradouro.setText(""+fornecedor.getLongradouro());
        FornecedorView.inputNumero.setText(""+fornecedor.getNumero());
        FornecedorView.inputBairro.setText(""+fornecedor.getBairro());
        FornecedorView.inputCidade.setText(""+fornecedor.getCidade());
        FornecedorView.comboEstado.setSelectedItem((String) fornecedor.getEstado());
        FornecedorView.inputCep.setText(""+fornecedor.getCep());
        FornecedorView.inputTelefone.setText(""+fornecedor.getTelefone());
        FornecedorView.inputEmail.setText(""+fornecedor.getEmail());
        FornecedorView.inputSituacao.setText(""+fornecedor.getSituacao());      
    }
    

}
