/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.vsn.view;

import br.com.vsn.controller.ClienteController;
import br.com.vsn.model.Cliente;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vitor
 */
public class PesquisarClienteView extends javax.swing.JInternalFrame {

    private static int id;
    SimpleDateFormat sdf;
    static Cliente cliente;
    
    public static int getId() {
        return id;
    }

    public static void setId(int id) {
        PesquisarClienteView.id = id;
    }
    
    
    /**
     * Creates new form PesquisarView
     */
    public PesquisarClienteView() {
        sdf = new SimpleDateFormat("dd/MM/yyyy");
        initComponents();
        
        Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
        double lar =d.getWidth();
        int alt = (int) d.getHeight();
        this.setLocation((int) ((lar - this.getSize().width) / 2), (alt - this.getSize().height)/6);
        initComponents();
        
        try {
            this.preencherTabela();
        } catch (Exception ex) {
            Logger.getLogger(PesquisarClienteView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setClosable(true);
        setTitle("Pesquisar Cliente");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "CPF", "Telefone", "Situação"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(10);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(200);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(80);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(80);
            jTable1.getColumnModel().getColumn(4).setPreferredWidth(80);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 868, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        if(evt.getClickCount() == 2){
          try {
              
                this.id = this.valorCollun();
                ClienteController cc = new ClienteController();
                cliente = cc.pesquisarUnico(id).get(0);
                try{
                    if(ClienteView.buttonSelecionar.getText().equals("Buscar")){
                    this.valoresInputCliente();
                    ClienteView.ativarInputCadastrar();
                    ClienteView.inputId.setEnabled(true);
                }else{
                    if(OrcamentoView.buttonCadastrar.getText().equals("Salvar")){
                        this.valoresInputOrcamento();
                    }
                }
                }catch(Exception e){
                    try{
                        this.valoresInputOrcamento();
                    }catch(Exception ex){
                        this.valoresInputOS();
                    }
                }
                this.dispose();
            } catch (Exception ex) {
                Logger.getLogger(PesquisarClienteView.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jTable1MouseClicked



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
    
    public void preencherTabela() throws Exception{
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        ClienteController cc = new ClienteController();
        DefaultTableModel modelo = (DefaultTableModel)jTable1.getModel();
        modelo.setNumRows(0);
        for(int i=0; i<cc.getClientes().size(); i++){
            modelo.addRow(new Object[]{
             cc.getClientes().get(i).getId(),
             cc.getClientes().get(i).getNome(),
             cc.getClientes().get(i).getCpf(),
             cc.getClientes().get(i).getTelefone(),
             cc.getClientes().get(i).getSituacao()
             });
        }
        
    }
    
    public int valorCollun(){
        int row = jTable1.getSelectedRow();
        Object value = null;
        String converteValueString = "";
         if (row > -1) { //então tem ítem selecionado
             value = jTable1.getValueAt(row, 0);
         }
         converteValueString = ""+value;
         id = Integer.parseInt(converteValueString);
         return id;
   }
    
    public void valoresInputCliente(){
        ClienteView.inputId.setText(""+cliente.getId());
        ClienteView.inputNome.setText(""+cliente.getNome());
        ClienteView.inputCpf.setText(""+cliente.getCpf());
        ClienteView.inputDtNascimento.setText(""+sdf.format(cliente.getDataNascimento().getTime()));
        ClienteView.comboSexo.setSelectedItem((String) cliente.getSexo());
        ClienteView.inputLongradouro.setText(""+cliente.getLongradouro());
        ClienteView.inputNumero.setText(""+cliente.getNumero());
        ClienteView.inputBairro.setText(""+cliente.getBairro());
        ClienteView.inputCidade.setText(""+cliente.getCidade());
        ClienteView.comboEstado.setSelectedItem((String)cliente.getEstado());
        ClienteView.inputCep.setText(""+cliente.getCep());
        ClienteView.inputTelefone.setText(""+cliente.getTelefone());
        ClienteView.inputEmail.setText(""+cliente.getEmail());
        ClienteView.inputSituacao.setText(""+cliente.getSituacao());  
    }
    
    public void valoresInputOrcamento(){
        OrcamentoView.inputCliente.setText(""+cliente.getNome());
        OrcamentoView.inputCpf.setText(""+cliente.getCpf());
    } 
    public void valoresInputOS(){
        OrdemServicoView.inputCliente.setText(""+cliente.getNome());
        OrdemServicoView.inputCpf.setText(""+cliente.getCpf());
    }

}
