/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.vsn.view;

import br.com.vsn.controller.ContaController;
import br.com.vsn.model.Conta;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vitor
 */
public class PesquisarContaReceberView extends javax.swing.JInternalFrame {

    private static int id;
    SimpleDateFormat sdf;
    NumberFormat formatter;
    static Conta conta;
    String valorCombo;
    ContaController cc;
    public static int validador=0;
    public static int getId() {
        return id;
    }

    public static void setId(int id) {
        PesquisarContaReceberView.id = id;
    }
    
    
    /**
     * Creates new form PesquisarView
     */
    public PesquisarContaReceberView() {
        sdf = new SimpleDateFormat("dd/MM/yyyy");
        formatter = new DecimalFormat("#0.00");
        initComponents();
        cc = new ContaController();
        Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
        double lar =d.getWidth();
        int alt = (int) d.getHeight();
        this.setLocation((int) ((lar - this.getSize().width) / 2), (alt - this.getSize().height)/6);
        initComponents();
        
        try {
            this.preencherTabela();
        } catch (Exception ex) {
            Logger.getLogger(PesquisarContaReceberView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        comboFiltro = new javax.swing.JComboBox<>();
        inputSelecionado = new javax.swing.JTextField();

        setClosable(true);
        setTitle("Pesquisar Contas a Receber");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Cliente", "Titulo", "Valor", "Parcelas", "Situação"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(10);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(200);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(200);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(80);
            jTable1.getColumnModel().getColumn(4).setPreferredWidth(80);
            jTable1.getColumnModel().getColumn(5).setPreferredWidth(80);
        }

        comboFiltro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Titulo", "Cliente" }));

        inputSelecionado.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        inputSelecionado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                inputSelecionadoKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(comboFiltro, 0, 247, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(inputSelecionado, javax.swing.GroupLayout.PREFERRED_SIZE, 612, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(inputSelecionado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        if(evt.getClickCount() == 2){
          try {
              
                this.id = this.valorCollun();
                ContaController cc = new ContaController();
                conta = cc.contaUnico(id).get(0);
                try{
                    if(validador == 1){
                        this.valoresInputRelatorioContasReceber();
                    }
                
                }catch(Exception e){
                   Logger.getLogger(PesquisarContaReceberView.class.getName()).log(Level.SEVERE, null, e);
                }
                this.dispose();
            } catch (Exception ex) {
                Logger.getLogger(PesquisarContaReceberView.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void inputSelecionadoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputSelecionadoKeyReleased
        try{
            valorCombo=comboFiltro.getSelectedItem().toString().toLowerCase();
            if(valorCombo.equals("titulo")){
                this.preencherTabelaFiltroTitulo();
            }else if (valorCombo.equals("cliente")){
                this.preencherTabelaFiltroCliente();
            }

        }catch(Exception e){
            Logger.getLogger(PesquisarClienteView.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_inputSelecionadoKeyReleased



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboFiltro;
    private javax.swing.JTextField inputSelecionado;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
    
    public void preencherTabela() throws Exception{
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        ContaController cc = new ContaController();
        DefaultTableModel modelo = (DefaultTableModel)jTable1.getModel();
        modelo.setNumRows(0);
        for(int i=0; i<cc.getContas().size(); i++){
            modelo.addRow(new Object[]{
             cc.getContas().get(i).getId(),
             cc.getContas().get(i).getCliente(),
             cc.getContas().get(i).getTitulo(),
             cc.getContas().get(i).getValor(),
             cc.getContas().get(i).getVezes(),
             cc.getContas().get(i).getSituacao()
             });
        }
        
    }
    
    public void preencherTabelaFiltroTitulo() throws Exception{
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        DefaultTableModel modelo = (DefaultTableModel)jTable1.getModel();
        modelo.setNumRows(0);
        for(int i=0; i<cc.pesquisarFiltroTitulo(inputSelecionado.getText()).size(); i++){
            modelo.addRow(new Object[]{
             cc.pesquisarFiltroTitulo(inputSelecionado.getText()).get(i).getId(),
             cc.pesquisarFiltroTitulo(inputSelecionado.getText()).get(i).getCliente(),
             cc.pesquisarFiltroTitulo(inputSelecionado.getText()).get(i).getTitulo(),
             cc.pesquisarFiltroTitulo(inputSelecionado.getText()).get(i).getValor(),
             cc.pesquisarFiltroTitulo(inputSelecionado.getText()).get(i).getVezes(),
             cc.pesquisarFiltroTitulo(inputSelecionado.getText()).get(i).getSituacao()
             });
        }
        
    }
    
    public void preencherTabelaFiltroCliente() throws Exception{
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        DefaultTableModel modelo = (DefaultTableModel)jTable1.getModel();
        modelo.setNumRows(0);
        for(int i=0; i<cc.pesquisarFiltroCliente(inputSelecionado.getText()).size(); i++){
            modelo.addRow(new Object[]{
             cc.pesquisarFiltroCliente(inputSelecionado.getText()).get(i).getId(),
             cc.pesquisarFiltroCliente(inputSelecionado.getText()).get(i).getCliente(),
             cc.pesquisarFiltroCliente(inputSelecionado.getText()).get(i).getTitulo(),
             cc.pesquisarFiltroCliente(inputSelecionado.getText()).get(i).getValor(),
             cc.pesquisarFiltroCliente(inputSelecionado.getText()).get(i).getVezes(),
             cc.pesquisarFiltroCliente(inputSelecionado.getText()).get(i).getSituacao()
             });
        }
        
    }
    
    public int valorCollun(){
        int row = jTable1.getSelectedRow();
        Object value = null;
        String converteValueString = "";
         if (row > -1) { //então tem ítem selecionado
             value = jTable1.getValueAt(row, 0);
         }
         converteValueString = ""+value;
         id = Integer.parseInt(converteValueString);
         return id;
   }
    
    public void valoresInputRelatorioContasReceber(){
        FiltroRelatorioContasReceberView.inputId.setText(""+conta.getId());
        FiltroRelatorioContasReceberView.inputTitulo.setText(""+conta.getTitulo());
        FiltroRelatorioContasReceberView.inputCliente.setText(""+conta.getCliente());
    }
    
}
